L3 milestone defined
pupilfirst/wd201-scripts pull request #125
Opened 2022-07-16 08:02 UTC by avishekjana

2022-07-20 10:59 UTC, mjzac requested changes
We can ask them to add logic to retrieve overdue, due later and due today items. Here is the previous WD201 milestone for the same level. https://www.pupilfirst.school/targets/1725

2022-08-01 04:02 UTC, avishekjana commented
@mjzac I've updated the milestone task, please review once.

2022-08-08 15:02 UTC, avishekjana commented
@mjzac @vikispeaks I've updated the milestone based on review. Please check once.

2022-08-08 15:02 UTC, avishekjana commented
@mjzac @vikispeaks I've updated the milestone based on review. Please check once.

2022-08-08 15:18 UTC, mjzac commented on nodejs-deep-dive/milestone/README.md
> +var todaydues = todos.dueToday()
```suggestion
let itemsDueToday = todos.dueToday()
```

2022-08-08 15:18 UTC, mjzac commented on nodejs-deep-dive/milestone/README.md
> +var formattedTodaydues = todos.toDisplayableList(todaydues)
```suggestion
let formattedItemsDueToday = todos.toDisplayableList(itemsDueToday)
```

2022-08-08 15:19 UTC, mjzac commented on nodejs-deep-dive/milestone/README.md
> +var laterdues = todos.dueLater()
```suggestion
let itemsDueLater = todos.dueLater()
```

2022-08-09 20:09 UTC, merged