Script added
pupilfirst/wd201-scripts pull request #126
Opened 2022-07-16 12:28 UTC by avishekjana

2022-07-20 12:40 UTC, mjzac requested changes

2022-07-20 12:40 UTC, mjzac commented on backend-dev-with-express/create-and-update-todo/README.md
> +  { description: Sequelize.TEXT, isComplete: { type: Sequelize.BOOLEAN, defaultValue: false }, dueDate: Sequelize.DATE }
```suggestion
  { description: Sequelize.TEXT, isComplete: { type: Sequelize.BOOLEAN, defaultValue: false }, dueDate: Sequelize.DATEONLY } 
```

2022-07-20 12:40 UTC, mjzac commented on backend-dev-with-express/create-and-update-todo/README.md
> +const Todo = sequelize.define(
`sequelize` and `Sequelize` are used here. It is better to include the `require` statements then.

2022-07-25 06:59 UTC, mjzac requested changes

2022-07-25 06:59 UTC, mjzac commented on backend-dev-with-express/create-and-update-todo/README.md
> +### Step 4: Complete the `update Todo` endpoint implementation
@avishekjana  The endpoint should be to mark a todo as complete, and not to update the description.

2022-07-27 10:26 UTC, avishekjana commented on backend-dev-with-express/create-and-update-todo/README.md
> +### Step 4: Complete the `update Todo` endpoint implementation
OK

2022-08-03 07:04 UTC, avishekjana commented on backend-dev-with-express/create-and-update-todo/README.md
> +const Todo = sequelize.define(
Done

2022-08-22 02:47 UTC, avishekjana commented on backend-dev-with-express/create-and-update-todo/README.md
> +const Todo = sequelize.define(
It's no more required, as I've used model generated by sequelize-cli.

2022-08-22 02:47 UTC, avishekjana commented
@mjzac Please review the script once again.

2022-08-23 12:12 UTC, mjzac requested changes

2022-08-24 03:08 UTC, avishekjana commented
Resolved all comments/feedbacks, closing this issue.

2022-08-24 03:08 UTC, merged