Authentication using passport
pupilfirst/wd201-scripts pull request #131
Opened 2022-07-18 02:34 UTC by avishekjana

2022-07-20 14:05 UTC, mjzac requested changes

2022-07-20 14:05 UTC, mjzac commented on user-authentication/create-user-signup-page/README.md
> +First, we will install few npm packages.
```suggestion
First, we will install a few npm packages.
```

2022-07-20 14:05 UTC, mjzac commented on user-authentication/create-user-signup-page/README.md
> +As we are managing our app's sessions with Passport, as soon as a user gets appropriately authenticated, a new session begins. At that time, we will serialize the user data to the session and the use
Maybe explain what is serializing and de-serializing ?

2022-07-24 05:38 UTC, avishekjana commented on user-authentication/create-user-signup-page/README.md
> +As we are managing our app's sessions with Passport, as soon as a user gets appropriately authenticated, a new session begins. At that time, we will serialize the user data to the session and the use
Added the definition, closing the PR.

2022-07-24 05:38 UTC, merged