view templates
pupilfirst/wd201-scripts pull request #138
Opened 2022-07-18 16:28 UTC by vikispeaks

2022-07-25 13:16 UTC, avishekjana requested changes

2022-07-25 13:16 UTC, avishekjana commented on ejs-templating/view-templates/README.md
> +If we open `localhost:3000` now we can see that the styling we created is applied to the page.
If we open `localhost:3000`, now we can see that the styling we created is applied to the page.

2022-07-25 13:16 UTC, avishekjana commented on ejs-templating/view-templates/README.md
> +Next to add JavaScript files, let us create a new **js** folder inside **public** folder and add `script.js` file inside it.
Next, to add JavaScript files, let us create a new **js** folder inside **public** folder and add `script.js` file inside it.

2022-07-25 13:16 UTC, avishekjana commented on ejs-templating/view-templates/README.md
> +Saving this file does not restart the nodemon as we have not configured it to listen to changes made in js files.
Saving this file does not restart the nodemon, as we have not configured it to listen to changes made in **js** files.

2022-07-25 13:16 UTC, avishekjana commented on ejs-templating/view-templates/README.md
> +Let us change that by updating the config of `package.json` scripts. Replace the `start` script with the below code.
Let us change that, by updating the config of `package.json` scripts. Replace the `start` script with the below code.

2022-07-25 13:16 UTC, avishekjana commented on ejs-templating/view-templates/README.md
> +In our case, let us create a Header for the Todo application with the text "This is my Todo Application" as a common view template.
In our case, let us create a **Header** for the Todo application with the text "This is my Todo Application" as a common view template.

2022-07-25 13:16 UTC, avishekjana commented on ejs-templating/view-templates/README.md
> +Let us create a new file called `header.ejs` in our application within the views folder.
Let us create a new file called `header.ejs` in our application within the `views` folder.

2022-07-26 17:02 UTC, vikispeaks commented on ejs-templating/view-templates/README.md
> +If we open `localhost:3000` now we can see that the styling we created is applied to the page.
Keeping this as it is. I think with respect to adding comma's the Language tool and Grammarly treat the sentence differently.

2022-07-26 17:03 UTC, vikispeaks commented on ejs-templating/view-templates/README.md
> +Next to add JavaScript files, let us create a new **js** folder inside **public** folder and add `script.js` file inside it.
Same as above.

2022-07-26 17:03 UTC, vikispeaks commented on ejs-templating/view-templates/README.md
> +Saving this file does not restart the nodemon as we have not configured it to listen to changes made in js files.
Done.

2022-07-26 17:03 UTC, vikispeaks commented on ejs-templating/view-templates/README.md
> +Let us change that by updating the config of `package.json` scripts. Replace the `start` script with the below code.
Same as above.

2022-07-26 17:04 UTC, vikispeaks commented on ejs-templating/view-templates/README.md
> +In our case, let us create a Header for the Todo application with the text "This is my Todo Application" as a common view template.
It is the same as stated review.

2022-07-26 17:05 UTC, vikispeaks commented on ejs-templating/view-templates/README.md
> +Let us create a new file called `header.ejs` in our application within the views folder.
Done.

2022-07-26 17:08 UTC, merged