deploy-application-to-heroku
pupilfirst/wd201-scripts pull request #152
Opened 2022-07-20 11:21 UTC by vikispeaks

2022-07-25 13:06 UTC, avishekjana requested changes

2022-07-25 13:06 UTC, avishekjana commented on ejs-templating/deploy-application-to-heroku/README.md
> +In this section, we will be looking at deploying our Rails application code to Heroku. Heroku is a PaaS that lets companies build, deliver, monitor and scale apps.
In this section, we will be looking at deploying our Node.Js application code to Heroku. Heroku is a PaaS that lets companies build, deliver, monitor and scale apps.

2022-07-25 13:06 UTC, avishekjana commented on ejs-templating/deploy-application-to-heroku/README.md
> +Update your scripts attribute in `package.json` to the above command. Basically, this command tells Heroku to run the command node app.js, which is the same command you’d use to run a node app on you
Update your scripts attribute in `package.json` to the above command. Basically, this command tells Heroku to run the command `node app.js`, which is the same command you’d use to run a node app on your terminal.

2022-07-25 13:06 UTC, avishekjana commented on ejs-templating/deploy-application-to-heroku/README.md
> +You can check if it installed successfully by going to your Heroku Dashboard and checking your app’s add-ons.
You can check if it is installed successfully, by going to your Heroku Dashboard and checking your app’s add-ons.

2022-07-26 17:52 UTC, vikispeaks commented on ejs-templating/deploy-application-to-heroku/README.md
> +In this section, we will be looking at deploying our Rails application code to Heroku. Heroku is a PaaS that lets companies build, deliver, monitor and scale apps.
Done.

2022-07-26 17:54 UTC, vikispeaks commented on ejs-templating/deploy-application-to-heroku/README.md
> +Update your scripts attribute in `package.json` to the above command. Basically, this command tells Heroku to run the command node app.js, which is the same command you’d use to run a node app on you
Done.

2022-07-26 17:55 UTC, vikispeaks commented on ejs-templating/deploy-application-to-heroku/README.md
> +You can check if it installed successfully by going to your Heroku Dashboard and checking your app’s add-ons.
Done.

2022-07-26 17:57 UTC, merged