Add tests for listing and creating todos
pupilfirst/wd201-scripts pull request #181
Opened 2022-07-25 07:58 UTC by mjzac

Fixes #65

2022-07-25 13:37 UTC, avishekjana requested changes

2022-07-25 13:37 UTC, avishekjana commented on backend-dev-with-express/add-tests/README.md
> +In this lesson, we will look into how to test the routes that we have created for our Todo web application. We first need to install a npm package `supertest` to help us with the testing. We will ins
In this lesson, we will look into how to test the routes that we have created for our Todo web application. First, we need to install a npm package `supertest` to help us with the testing. We will install it as a development dependency.

2022-07-25 13:37 UTC, avishekjana commented on backend-dev-with-express/add-tests/README.md
> +We can also make sure the response contains data in a specified format that we require. The todo items are supposed to be returned as a json object with following structure:
We can also make sure the response contains data in a specified format that we require. The To-do items are supposed to be returned as a JSON object with the following structure:

2022-07-25 13:37 UTC, avishekjana commented on backend-dev-with-express/add-tests/README.md
> +Next, let's add a test to check the creation of todo. Since, we have protected our todo creation route using a CSRF token, we have to make sure we pass in the token in the request as well. To help us
Next, let's add a test to check the creation of to-do. Since, we have protected our to-do creation route using a CSRF token, we have to make sure we pass the token in the request as well. To help us with that, we will install another package named `cheerio`. We will simply send a request to list the to-dos, extract the CSRF token from the response, and then send out the actual request to create the to-do.

2022-07-25 13:37 UTC, avishekjana commented on backend-dev-with-express/add-tests/README.md
> +We just added a function to extract the csrfToken from the html response. Let's add a test now. We will require cookies as well. So we will use a super request `agent`.
We just added a function to extract the `csrfToken` from the HTML response. Let's add a test now. We will require cookies as well. So we will use a super request `agent`.

2022-07-25 13:37 UTC, avishekjana commented on backend-dev-with-express/add-tests/README.md
> +You have now added tests to back your code. This would ensure the code will work as it is intended.
There are a lot of things going on, better if we upgrade the script as a Video lesson.

2022-07-25 22:41 UTC, mjzac commented on backend-dev-with-express/add-tests/README.md
> +You have now added tests to back your code. This would ensure the code will work as it is intended.
Let the first batch of students try to follow the text lesson. If they face issues or requires a video, we can create a video lesson.

2022-08-01 09:57 UTC, avishekjana commented on backend-dev-with-express/add-tests/README.md
> +You have now added tests to back your code. This would ensure the code will work as it is intended.
ok

2022-08-01 09:58 UTC, avishekjana approved these changes

2022-08-01 09:59 UTC, merged