showing messages to user
pupilfirst/wd201-scripts pull request #192
Opened 2022-07-28 10:49 UTC by vikispeaks

2022-08-03 11:18 UTC, mjzac requested changes

2022-08-03 11:18 UTC, mjzac commented on user-authentication/showing-messages-to-user/README.md
> +In our application, we can show messages when users to add or remove items from a to-do list. We can also use it to alert the user every time they log in or out, along with showing any error messages
```suggestion
In our application, we can show messages when users add or remove items from a to-do list. We can also use it to alert the user every time they log in or out, along with showing any error messages.
```

2022-08-03 11:18 UTC, mjzac commented on user-authentication/showing-messages-to-user/README.md
> +This command adds `connect-flash` module to your application and you can start using this on your `index.js`
```suggestion
This command adds `connect-flash` module to your application and you can start using this in your `index.js`
```

2022-08-03 11:18 UTC, mjzac commented on user-authentication/showing-messages-to-user/README.md
> +Next let us create a session function to be used within the app using the below code.
The student will already have set up session from previous lessons. See https://github.com/pupilfirst/wd201-scripts/blob/v2/user-authentication/authentication-using-passport/README.md#now-lets-start-with-the-implementation

2022-08-18 09:07 UTC, vikispeaks commented on user-authentication/showing-messages-to-user/README.md
> +Next let us create a session function to be used within the app using the below code.
Agree. This will just ask the user to update the same function with addional params.

2022-08-18 09:11 UTC, merged