Add async await lesson
pupilfirst/wd201-scripts pull request #227
Opened 2022-09-09 07:57 UTC by mjzac

2022-09-09 20:42 UTC, reenas commented
@vikispeaks @avishekjana Please prioritize this review and merge.

2022-09-10 13:11 UTC, avishekjana requested changes

2022-09-10 13:28 UTC, mjzac commented on nodejs-deep-dive/callbacks-promise-async-await/README.md
> +```
I have added a rejection example.

2022-09-10 13:31 UTC, mjzac commented on nodejs-deep-dive/callbacks-promise-async-await/README.md
> +
I thought it would be better to use some real world example rather than printing generic messages. Do you have some simpler examples in mind? @avishekjana @vikispeaks

2022-09-11 15:45 UTC, reenas commented
@mjzac I was going through this lesson and example. I feel the example itself is quite intuitive. However, this will need a video where you can describe properly what is exactly happening here, so students understand what is being called/returned where and how. 

For me, the next steps got confusing:
- next(`https://image.example.com/${userID}`);
- next(`Data from ${imageURL}`);

2022-09-22 07:18 UTC, merged