Closure script revised with simpler example
pupilfirst/wd201-scripts pull request #27
Opened 2022-07-06 04:07 UTC by avishekjana

2022-07-07 03:26 UTC, mjzac requested changes
The explanations would become much simpler by saying  parent value is captured and stored till the child go out of scope or destroyed.

2022-07-07 03:26 UTC, mjzac commented on nodejs-deep-dive/closures-in-js/README.md
> +I will explain in clear terms what **closure** is, and how you can easily relate it to real-world.
```suggestion
```

2022-07-07 03:26 UTC, mjzac commented on nodejs-deep-dive/closures-in-js/README.md
> +I guess you haven't heard of this term *closure* previously, and frankly it is not very much self-explanatory as well. From today onwards, you can remember it with a fairly simple term (or synonym) -
```suggestion
You probably haven't heard of the term *closure* previously, and it is not very self-explanatory either. From today onwards, you can remember it with a reasonably simple term (or synonym) - Legacy! Why? Let's find out.
```

2022-07-07 03:26 UTC, mjzac commented on nodejs-deep-dive/closures-in-js/README.md
> +legacy(); // Output: I have: Home Sweet Home iPhone 13
The example seems contrived.. I know it is a hard topic to write a simple example. But wouldn't a greet function be enough?

```js
function generateGreetings(name) {
  function spanish() {
    console.log(`Hola ${name}!`);
  }
  function english() {
    console.log(`Hello ${name}!`);
  }
  return {spanish, english};
};

const name = 'John';
const greetings = generateGreetings(name);

console.log(typeof(greetings.spanish)); // function

greetings.spanish(); // Hola John!
greetings.english(); // Hello John!
```

2022-07-16 06:28 UTC, avishekjana commented
@mjzac I've updated the script as per your review. Please check once.

2022-07-19 03:37 UTC, mjzac approved these changes
Looks good to me.

2022-07-20 21:20 UTC, merged