Introduction to Node.Js (First version)
pupilfirst/wd201-scripts pull request #5
Opened 2022-06-22 17:02 UTC by avishekjana

2022-07-04 18:37 UTC, vikispeaks requested changes
Please update all references to Node.js right.

2022-07-04 18:37 UTC, vikispeaks commented on introduction-to-nodejs/what-is-node-js-with-installation/README.md
> +In this course we will learn about a JavaScript framework called Node.Js. I'm assuming that you've already completed the [Web Development 101 course](https://www.pupilfirst.school/courses/1087/curric
```suggestion
In this course, we will learn about a JavaScript framework called Node.js. I'm assuming that you've already completed the [Web Development 101 course](https://www.pupilfirst.school/courses/1087/curriculum). This means that you're quite familiar with JavaScript, right?
```

2022-07-04 18:37 UTC, vikispeaks commented on introduction-to-nodejs/what-is-node-js-with-installation/README.md
> +To recap, JavaScript is a **Programming Language**,  that runs on end user's browser, and allows us to calculate, manipulate and validate data. Where HTML and CSS are languages that give structure an
```suggestion
To recap, JavaScript is a **Programming Language**,  that runs on the end user's browser, and allows us to calculate, manipulate and validate data. Where HTML and CSS are languages that give structure and style to web pages, JavaScript improves the user experience of the web page by converting it from a static page into an interactive one.
```

2022-07-04 18:37 UTC, vikispeaks commented on introduction-to-nodejs/what-is-node-js-with-installation/README.md
> +Now, have you ever wondered, the static HTML webpages or the forms that you've designed, how to make them dynamic? How to store that form's data in a database? Or what if, you want to send an confirm
```suggestion
Now, have you ever wondered, about the static HTML webpages or the forms that you've designed, and how to make them dynamic? How to store that form's data in a database? Or, what if, you want to send a confirmation email to a user who submits the form? 
```

2022-07-04 18:37 UTC, vikispeaks commented on introduction-to-nodejs/what-is-node-js-with-installation/README.md
> +Web browsers communicate with web servers using the HyperText Transfer Protocol (HTTP). When you click a link on a web page or submit a form, an HTTP request is sent from your browser to the target w
```suggestion
Web browsers communicate with web servers using the Hypertext Transfer Protocol (HTTP). When you click a link on a web page or submit a form, an HTTP request is sent from your browser to the target web server.
```

2022-07-04 18:37 UTC, vikispeaks commented on introduction-to-nodejs/what-is-node-js-with-installation/README.md
> +A dynamic website is one where some response content is generated dynamically, only when needed. On a dynamic website, the HTML pages are normally created by fetching data from a database, then inser
```suggestion
A dynamic website is one where some response content is generated dynamically, only when needed. On a dynamic website, the HTML pages are normally created by fetching data from a database, and then inserting that data into certain placeholders in HTML template. 
```

2022-07-04 18:37 UTC, vikispeaks commented on introduction-to-nodejs/what-is-node-js-with-installation/README.md
> +Now imagine, what if you could use your JavaScript knowledge to write back-end or server-side logic? This is where the role of Node.Js comes in.
```suggestion
Now imagine, what if you could use your JavaScript knowledge to write back-end or server-side logic? This is where the role of Node.js comes in.
```

2022-07-04 18:37 UTC, vikispeaks commented on introduction-to-nodejs/what-is-node-js-with-installation/README.md
> +Before Node.JS, you could only run JavaScript in the browser. In 2009, Ryan Dahl came up with the idea of executing JavaScript code on the server-side, by using Chrome's v8 engine. Node.Js is a platf
```suggestion
Before Node.js, you could only run JavaScript in the browser. In 2009, Ryan Dahl came up with the idea of executing JavaScript code on the server-side, by using Chrome's v8 engine. Node.js is a platform which is actually built on top of **Chrome's JavaScript Runtime environment**. Which makes it blazing fast when it comes down to the performance.
```

2022-07-04 18:37 UTC, vikispeaks commented on introduction-to-nodejs/what-is-node-js-with-installation/README.md
> +Every browser has their own JavaScript engine that converts JavaScript into code that a computer can understand. For example, Microsoft Edge uses Chakra, Firefox uses spidermonkey, and chrome uses V8
```suggestion
Every browser has their own JavaScript engine that converts JavaScript into code that a computer can understand. For example, Microsoft Edge uses Chakra, Firefox uses SpiderMonkey, and chrome uses V8.
```

2022-07-04 18:37 UTC, vikispeaks commented on introduction-to-nodejs/what-is-node-js-with-installation/README.md
> +In this video, I'll show you, how easily you can setup your computer to write Node.Js applications.
```suggestion
In this video, I'll show you, how easily you can setup your computer to write Node.js applications.
```

2022-07-04 18:37 UTC, vikispeaks commented on introduction-to-nodejs/what-is-node-js-with-installation/README.md
> +There are a number of different ways you can install Node.Js on your system. However, one of the most popular is *nvm.* NVM stands for Node.Js Version Manager. It allows us to quickly install and use
```suggestion
There are a number of different ways you can install Node.js on your system. However, one of the most popular is *nvm.* NVM stands for Node Version Manager. It allows us to quickly install and use different versions of Node.js in our computer.
```

2022-07-04 18:37 UTC, vikispeaks commented on introduction-to-nodejs/what-is-node-js-with-installation/README.md
> +**npm** is a package manager for the JavaScript programming language. It consists of a command line client, also called **npm**, and an online database of public and private packages. Open source dev
```suggestion
**npm** is a package manager for the JavaScript programming language. It consists of a command-line client, also called **npm**, and an online database of public and private packages. Open-source developers use npm to share and borrow packages.
```

2022-07-06 02:56 UTC, avishekjana commented
@vikispeaks, I've made all suggested changes, please approve and close the PR's

2022-07-07 16:50 UTC, merged