Introduction to git
pupilfirst/wd201-scripts pull request #7
Opened 2022-06-25 15:56 UTC by avishekjana

2022-07-07 02:52 UTC, mjzac requested changes

2022-07-07 02:52 UTC, mjzac commented on introduction-to-nodejs/intro-to-git/README.md
> +As we all know, any software product is developed by several engineers. A version control system helps these developers to track and manage changes done to the software code. So they can simultaneous
```suggestion
As we all know, any software product is developed by several engineers. A version control system helps these developers to track and manage changes done to the software code. So they can simultaneously work on the same project without interfering with another person's work.
```

2022-07-07 02:52 UTC, mjzac commented on introduction-to-nodejs/intro-to-git/README.md
> +Normally most people gets confused between Git and GitHub. They think both are same. But that's not true. Git is the Vision Control System which you can install in your computer to manage source code
```suggestion
Usually, most people get confused between Git and GitHub. They think both are the same. But that's not true. Git is a Version Control System that you can install on your computer to manage source code. In comparison, GitHub is a hosting service for projects that use git.
```

2022-07-07 02:52 UTC, mjzac commented on introduction-to-nodejs/intro-to-git/README.md
> +With git you can:
```suggestion
With git, you can:
```

2022-07-07 02:52 UTC, mjzac commented on introduction-to-nodejs/intro-to-git/README.md
> +- Revert back to previous state of a file, at different points in time
```suggestion
- Revert to previous state of a file at different points in time
```

2022-07-07 02:52 UTC, mjzac commented on introduction-to-nodejs/intro-to-git/README.md
> +GitHub is a Git hosting repository that allows us to share a project with other developers.
```suggestion
GitHub is a Git hosting service that allows us to share a project with other developers. 
```

2022-07-07 02:52 UTC, mjzac commented on introduction-to-nodejs/intro-to-git/README.md
> +First, follow the link given below to install git in your system. This link will lead you to Git's official website. Check the installation steps based on the operating system you have.
Probably it would be better if we include the installation step here itself instead of asking them to follow a link?

2022-07-07 02:52 UTC, mjzac commented on introduction-to-nodejs/intro-to-git/README.md
> +Great! see you in the next lesson.
```suggestion
Great! Now you have both Git and GitHub ready. See you in the next lesson.
```

2022-07-16 06:09 UTC, avishekjana commented on introduction-to-nodejs/intro-to-git/README.md
> +First, follow the link given below to install git in your system. This link will lead you to Git's official website. Check the installation steps based on the operating system you have.
@mjzac I've revised the script with installation steps, please check once.

2022-07-17 11:45 UTC, merged